settings_version: 0.0.5
datasets_dir: /app/datasets
weights_dir: weights
runs_dir: runs
uuid: 1f382577d5d1a1b666400dfabf95bf1a6cfd7bb49c84294b58d418b4de23e685
sync: true
api_key: ''
openai_api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
vscode_msg: true
